version: "3.9"

services:
  api-main:
    build:
      context: ..
      dockerfile: Api/Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: host.docker.internal
      DB_NAME: postgres
      DB_PORT: 5432
      APP_READ_ONLY: "false"
    expose:
      - "8080"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api-main
      - pgadmin
    ports:
      - "8088:80"
    volumes:
      - ./nginx/lab4.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    expose:
      - "80"
